
# ---------------Active profiles-------------
#i just commented 4th line
#spring.profiles.active=@spring.profiles.active@
# spring.profiles.active=dev
spring.profiles.active=dev

#------------------HIBERNATE-----------------
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
# spring.jpa.open-in-view = true
# spring.jpa.show-sql = true
# spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8


#---------------File upload-----------------
server.tomcat.connection-timeout=120s
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


# ------------------Server-----------------
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,application/javascript,application/json


# ---------------Security-----------------
logging.level.root=ERROR
# logging.level.org.springframework.security=DEBUG


# -------------------JWT--------------------
jkt.app.jwtCookieName= _jkt_at
jkt.app.jwtSecret= 7fb14ecce2ad28938d9ab8c44390e28d3ecb6d0deb55dbe3bf49398098f058fc2b30aafac8103e17df6e5690a0767b2c3f82dbfae66203a9ef0a409d2f08a86b4a9ee33535bcbc8af48b8dea3cbe05b3e714505f765699d6519d3bff083251ecf8c2b8ac224e3c484cae344fc631354994e2415fa4fbc609473e8cd5c6b5695035ad90c8ac1be3f2941295ab714891986a062a5e76466a485363eded9da3b4fa30427a762c7e20f1224d81855ed31a5e680318d2ee3731d237a1a4616e1140cd21ab5993390daf00a5d63da5df76ea437bb3a57d4c98a5e705b9c95dc07e36496dd861fa6ef4f35f4c54aa7d39ba9668e853117efcc73c80b762887f75f72f29
jkt.app.jwtExpirationMs= 86400000
jkt.app.jwtRefreshExpirationMs=604800000