spring.datasource.url=jdbc:postgresql://10.194.81.95:5432/jktourism
spring.datasource.username = postgres
spring.datasource.password=b@TWaM!mgs#22#$
spring.jpa.hibernate.ddl-auto = update

frontEndUrl=https://ms6.pmgatishakti.gov.in,http://localhost:9999
geoserverURL=http://10.194.81.120:80/geoserver/multimodel/wms

mediaPath=/srv/staging2/JKTourismFiles

backendPath=https://staging2.pmgatishakti.gov.in/jktourism-api