# -------------------Server------------------
server.port = 3500
server.address=0.0.0.0
# -------------------PostgreSQL--------------
spring.datasource.url = jdbc:postgresql://localhost:5432/JKTourism?currentSchema=public
spring.datasource.username = postgres
spring.datasource.password = postgres

# ------------Front End (nextjs)------------
frontEndUrl=http://localhost:5173,http://localhost:3000

# ---------------Geoserver------------------
geoserverURL=http://localhost:8080/geoserver/cite/wms

# -------------File Upload------------------
mediaPath=C:\\Users\\bisag\\Desktop\\JKTourismFiles
# mediaPath=C:\\Users\\aksha\\Desktop\\JKTourismFiles

# backendPath=http://localhost:3500
backendPath=https://staging2.pmgatishakti.gov.in/jktourism-api

spring.data.redis.host=192.168.0.253
# spring.data.redis.host=localhost
spring.data.redis.port=6379